### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by sadikovi**
This PR fixes build warnings that are observed when running `cargo build`. This does not include fixes for `src/parquet_thrift/parquet.rs`. I opened pull request in Thrift repository to fix this. This will require to pull master and re-run `make install` for thrift, after that regenerated parquet.rs should not output any warnings.

### CODE REVIEW

**Comment by sadikovi** [comment]
I suggest we wait until pull request 1360 in apache/thrift is merged.

I tested fix locally with updated fix - get 0 warnings.

**Comment by sunchao** [comment]
@sadikovi thanks! PR looks good to me. Will merge once the Thrift PR is committed.

**Comment by sadikovi** [comment]
PR (https://github.com/apache/thrift/pull/1360) has been merged, so now if you pull latest thrift master and this patch, it should show no warnings!

**Comment by sunchao** [comment]
Merged!

**Pull request merged**
