### PR TITLE
Deploy documentation to github pages

### PR DESCRIPTION
**Pull request by sunchao**

### CODE REVIEW

**Comment by sunchao** [comment]
Followed the steps you provided @sadikovi . Can you review this? Thanks!

**Comment by sadikovi** [comment]
Would love to get this merged, so we can close release 0.2.0.

Are we going to release 0.3.0 right after this PR is merged? That would be great, IMHO.

**Comment by sunchao** [comment]
Thanks @sadikovi . Let me merge this first to see if it works.

> Have you considered adding badges for documentation or update existing links?

Will add once this works.

**Comment by sadikovi** [comment]
Cheers. You might need to retag 0.2.0 or create a new tag, so it has the latest changes. Can’t wait to see docs!

**Comment by sunchao** [comment]
> Are we going to release 0.3.0 right after this PR is merged? That would be great, IMHO.

Hmm I haven't thought about it. Is that because we want to have the doc cover the latest changes? we can do a 0.2.1 release maybe?

**Comment by sadikovi** [comment]
Nah, I was just thinking there were a lot of changes already for 0.3.0. But I am happy either way!

**Comment by sunchao** [comment]
Cool. I just added a badge for the master branch doc. For some reason, the doc for 0.2.0 didn't show up. Do you have any idea?

**Comment by sadikovi** [comment]
It uses old Travis file. You would need to run it on the latest changes. I think that’s why.

**Pull request merged**
