### PR TITLE
Fix travis code coverage

### PR DESCRIPTION
**Pull request by sunchao**
The installation steps for cargo-travis were deleted by mistake.
The CI jobs were succeeding because it was using cache, but recently
started to fail because the cache is gone. This fixes it.

### CODE REVIEW

**Comment by sadikovi** [comment]
Well done! I actually did not notice it:) Thanks for fixing the issue.

**Comment by sunchao** [comment]
NP. Seems it is still failing for that `types.h not found` error. Looking...

**Comment by sadikovi** [comment]
I was thinking if it could be related to using `travis-cargo test` command instead of `cargo test`, but it could be something else indeed (looks like that is the only thing that is different between the two conf files).

**Comment by sunchao** [comment]
Yeah the error was strange - seems it is trying to compile against x86 but the docker environment was set up for x86_64.

**Comment by sunchao** [comment]
The failure was caused by https://github.com/SimonKagstrom/kcov/issues/262, and the original commit that caused the issue was reverted. Coveralls worked in the latest build.

**Comment by sadikovi** [comment]
Thanks. Well done!

**Pull request merged**
